services:
  db:
    image: postgres:16-alpine3.21
    container_name: fastapi_postgres
    env_file:
      - src/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi_app
    command: >
      sh -c "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.app:app --bind 0.0.0.0:8001"
    ports:
      - 8001:8001
    depends_on:
      - db
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger_for_fapi
    ports:
      - "16686:16686"
      - "6831:6831/udp"

volumes:
  postgres_data:
